#!/bin/bash
NAME="system"
set -e
source ./common
init_variables

rm -f ${WORK_DIR}/${NAME}*.*

echo "[${NAME}] building ${NAME}_startup.s ..."
arm-none-eabi-as ${MACHINE_FLAG} -g ${SRC_DIR}/${NAME}_startup.s -o ${WORK_DIR}/${NAME}_startup.o

echo "[${NAME}] building ${NAME}_main.c ..."
arm-none-eabi-gcc -c ${MACHINE_FLAG} ${CFLAGS} -g ${SRC_DIR}/${NAME}_main.c -o ${WORK_DIR}/${NAME}_main.o

# system.elf and system.map
#
cd ${WORK_DIR}
echo "[${NAME}] generating ${NAME}.elf (and memory map file) ..."
arm-none-eabi-ld -T ${SRC_DIR}/${NAME}.ld -Map ${NAME}.map ${NAME}_main.o ${NAME}_startup.o -o ${NAME}.elf

# system.bin
#
arm-none-eabi-objcopy -O binary ${NAME}.elf ${NAME}.bin

/usr/local/Cellar/qemu/2.4.0/bin/qemu-system-arm \
	-M versatilepb \
	-m 128M \
	-nographic \
	-kernel ${WORK_DIR}/${NAME}.bin \
	-serial telnet:localhost:1235,server

