#!/bin/bash

./build_app
./build_system

#/usr/local/Cellar/qemu/2.4.0/bin/qemu-system-arm \
/Users/yagamy/Work/workspaces/github/qemu/arm-softmmu/qemu-system-arm \
	-M versatilepb \
	-m 128M \
	-nographic \
	-kernel ./work/system.bin \
	-serial telnet:localhost:1235,server

