// Generated by LiveScript 1.4.0
(function(){
  var yapps, app;
  yapps = require('yapps');
  app = yapps.createApp('web', {
    plugins: [],
    verbose: true
  });
  app.init(function(err){
    if (err != null) {
      console.error("exit with err: " + err);
    }
    if (err != null) {
      return process.exit(1);
    }
    return INFO("App ready!!");
  });
}).call(this);
